{
 "title": "BigQuery & DBT metrics",
 "time": { "from": "now-1y", "to": "now - 1d" },
 "templating": {
  "list": [
   {
    "name": "usernames",
    "label": "Usernames",
    "query": {}
   },
   {
    "name": "user_type",
    "label": "User Type",
    "query": {}
   },
   { "name": "bigquery_datasource", "label": "BigQuery Datasource", "query": "grafana-bigquery-datasource" }
  ]
 },
 "panels": [
  { "title": "Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estimated Total Cost (Yesterday)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "rawSql": "Select sum(total_estimated_cost_usd) as total_cost\nfrom `leaner_query.rpt_bigquery_usage_cost_daily`\nwhere report_date = current_date() - 1"
    }
   ]
  },
  {
   "title": "Total Queries Run Yesterday",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "rawSql": "Select sum(total_queries_run) as total_query_count\nfrom `leaner_query.rpt_bigquery_usage_cost_daily`\nwhere report_date = current_date() - 1"
    }
   ]
  },
  {
   "title": "Cost Trends by Client Type",
   "type": "table",
   "description": "Cost changes (7 day and 30 day) for clients that have accumulated at least $1 in query costs over the past day.",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with aggs as(\n  select\n    report_date,\n    client_type,\n    total_estimated_cost_usd,\n    avg(total_estimated_cost_usd) over (partition by client_type order by report_date rows between 6 preceding and current row) as seven_day_avg,\n    avg(total_estimated_cost_usd) over (partition by client_type order by report_date rows between 29 preceding and current row) as thirty_day_avg\n  from `leaner_query.rpt_bigquery_usage_cost_daily`\n  where report_date >= current_date - 31\n)\nselect\n  client_type,\n  aggs.total_estimated_cost_usd,\n  thirty_day_avg,\n  seven_day_avg,\n  safe_divide((total_estimated_cost_usd - seven_day_avg), seven_day_avg) as seven_day_change,\n  safe_divide((total_estimated_cost_usd - thirty_day_avg), thirty_day_avg) as thirty_day_change\nfrom aggs\nwhere report_date = current_date - 1\nand aggs.total_estimated_cost_usd > 1.0\norder by 2 desc"
    }
   ]
  },
  {
   "title": "Aggregated Costs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with total_costs as(\n  select\n  timestamp(report_date) as report_date\n  , sum(total_estimated_cost_usd) as sum_cost\nfrom `leaner_query.rpt_bigquery_user_metrics_daily`\nwhere username in ($usernames)\n  and user_type in ($user_type)\n  and $__timeFilter(timestamp(report_date)) \n  -- and report_date != current_date\ngroup by 1\n)\nSelect *,\nCase \n  when Lag(report_date, 7) over(order by report_date) is null then null\n  else avg(sum_cost) over(order by report_date rows between 6 preceding and current row)\nEnd as rolling_avg  \nfrom total_costs\nORDER BY 2\n"
    }
   ]
  },
  {
   "title": "Individual Users and Costs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select\n  timestamp(report_date) as report_date\n  , user_type\n  , username\n  , sum(total_estimated_cost_usd) as sum_cost\nfrom `leaner_query.rpt_bigquery_user_metrics_daily`\nwhere username in ($usernames)\n  and user_type in ($user_type)\n  and $__timeFilter(timestamp(report_date)) \n  -- and report_date != current_date\ngroup by 1,2,3\norder by 3"
    }
   ]
  },
  {
   "title": "Costs by Client Type",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select\n  timestamp(report_date) as report_date\n  , client_type\n  , total_estimated_cost_usd as sum_cost\nfrom `leaner_query.rpt_bigquery_usage_cost_daily`\nwhere $__timeFilter(timestamp(report_date)) \n-- group by 1,2\norder by 1"
    }
   ]
  },
  {
   "title": "Dbt Costs",
   "type": "timeseries",
   "description": "Daily costs associated with dbt runs, tests, and snapshots.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select\n  timestamp(report_date) as report_date,\n  round(sum(total_estimated_dbt_run_cost_usd), 2) as daily_build_cost,\n  round(sum(total_estimated_dbt_test_cost_usd), 2) as daily_test_cost,\n  round(sum(total_estimated_dbt_snapshot_cost_usd), 2) as daily_snapshot_cost\nfrom `leaner_query.rpt_bigquery_dbt_metrics_daily`\nwhere $__timeFilter(timestamp(report_date)) \ngroup by 1\n\n"
    }
   ]
  },
  {
   "title": "Top 25 Expensive DBT Runs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select distinct\n  dbt_model_name,\n  total_estimated_dbt_run_cost_usd,\n  average_build_cost,\n  total_dbt_builds\nfrom `leaner_query.rpt_bigquery_dbt_metrics_daily`\nwhere report_date = current_date - 1\norder by 2 desc\nlimit 25"
    }
   ]
  },
  {
   "title": "Top 25 Expensive DBT Tests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select distinct\n  dbt_model_name,\n  total_estimated_dbt_test_cost_usd,\n  average_test_cost,\n  total_dbt_tests\nfrom `leaner_query.rpt_bigquery_dbt_metrics_daily`\nwhere report_date = current_date - 1\norder by 2 desc\nlimit 25"
    }
   ]
  },
  {
   "title": "Top 25 Expensive DBT Snapshots",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select distinct\n  dbt_model_name,\n  total_estimated_dbt_snapshot_cost_usd,\n  average_snapshot_cost,\n  total_dbt_snapshots\nfrom `leaner_query.rpt_bigquery_dbt_metrics_daily`\nwhere report_date = current_date - 1\norder by 2 desc\nlimit 25"
    }
   ]
  },
  { "title": "Usage Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Individual Users and Errors",
   "type": "timeseries",
   "description": "Tracks the number of BigQuery errors for each user on a given day.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "select\n  timestamp(report_date) as report_date\n  , user_type\n  , username\n  , total_errors\nfrom `leaner_query.rpt_bigquery_user_metrics_daily`\nwhere username in ($usernames)\n  and user_type in ($user_type)\n  and $__timeFilter(timestamp(report_date)) \n  -- and report_date != current_date\n-- group by 1,2,3\norder by 3"
    }
   ]
  },
  {
   "title": "Percent Total of Individual Users and Errors",
   "type": "timeseries",
   "description": "Tracks the percent total of BigQuery errors for each user on a given day.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with base as (\n  select\n    timestamp(report_date) as report_date\n    , user_type\n    , username\n    , total_errors\n  from `leaner_query.rpt_bigquery_user_metrics_daily`\n  where username in ($usernames)\n  and user_type in ($user_type)\n  and $__timeFilter(timestamp(report_date)) \n),\n\ntotal_errors as (\n  select\n    report_date,\n    sum(total_errors) as num_total_errors\n  from base\n  group by 1\n)\n\nselect\n  base.report_date,\n  base.user_type,\n  base.username,\n  round(base.total_errors / total_errors.num_total_errors, 2) as perc_total_errors\nfrom base\nleft join total_errors\n  on base.report_date = total_errors.report_date\norder by 4 desc\n"
    }
   ]
  },
  {
   "title": "Distinct Users by Layer",
   "type": "timeseries",
   "description": "Shows how many users have queried each of the layers for a given day. Users can query more than one layer.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "\n  select\n    timestamp(report_date) as report_date\n    -- , count(distinct if(total_tables_used > 0, username, null)) as users\n    , count(if(total_prod_tables_used > 0, 1, null)) as used_prod\n    , count(if(total_stage_tables_used > 0, 1, null)) as used_stage\n    , count(if(total_raw_tables_used > 0, 1, null)) as used_raw\n  from `leaner_query.rpt_bigquery_user_metrics_daily`\n  where username in ($usernames)\n    and user_type in ($user_type)\n    and $__timeFilter(timestamp(report_date)) \n  group by 1\n\n"
    }
   ]
  },
  {
   "title": "Percent layer use",
   "type": "timeseries",
   "description": "Shows what percentage (of the total use) each data layer was used in queries.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "with daily_totals as(\nSELECT \n report_date,\n sum(total_prod_tables_used) as total_prod_tables_used,\n sum(total_stage_tables_used) as total_stage_tables_used,\n sum(total_raw_tables_used) as total_raw_tables_used,\n FROM `leaner_query.rpt_bigquery_user_metrics_daily` \n  where username in ($usernames)\n    and user_type in ($user_type)\n    and $__timeFilter(timestamp(report_date)) \n group by 1\n ),\nadd_total_use as(\n  select *,\n    daily_totals.total_prod_tables_used + daily_totals.total_stage_tables_used + daily_totals.total_raw_tables_used as total_tables_used\n  from daily_totals\n)\nselect \n  timestamp(report_date) as report_date,\n  add_total_use.total_prod_tables_used / add_total_use.total_tables_used as `Percent Prod Used`,\n  add_total_use.total_stage_tables_used / add_total_use.total_tables_used as `Percent Stage Used`,\n  add_total_use.total_raw_tables_used / add_total_use.total_tables_used as `Percent Raw Used`,\nfrom add_total_use;"
    }
   ]
  },
  {
   "title": "Table usage by layer",
   "type": "barchart",
   "description": "Shows the total number of times each data layer was used in queries.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "location": "US",
     "rawSql": "SELECT \n timestamp(report_date),\n sum(total_prod_tables_used) as `Total prod tables used`,\n sum(total_stage_tables_used) as `Total stage tables used`,\n sum(total_raw_tables_used) as `Total rawtables used`,\n FROM `leaner_query.rpt_bigquery_user_metrics_daily` \n  where username in ($usernames)\n    and user_type in ($user_type)\n    and $__timeFilter(timestamp(report_date)) \n group by 1"
    }
   ]
  },
  {
   "title": "Top 25 Riskiest Tables",
   "type": "table",
   "description": "This table contains the top 25 tables in your BQ instance which have the highest threat levels.\n\nA table risk score is determined by how many external systems are connected via service accounts, the median cost to query, median cost to build, and the median daily errors incurred.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "targets": [
    {
     "location": "US",
     "rawSql": "select distinct\n  concat(split(table_name, '/')[safe_offset(3)], '.', split(table_name, '/')[safe_offset(5)]) as table_name\n, threat_score\nfrom `leaner_query.rpt_bigquery_table_usage_daily`\nwhere report_date = current_date -1\n  and threat_score is not null\norder by threat_score desc\nlimit 25 -- maybe a rank instead of this later on"
    }
   ]
  },
  {
   "title": "Top 25 Important Tables",
   "type": "table",
   "description": "This table contains the top 25 tables in your BQ instance which have the highest importance levels.\n\nThe importance calculation is a combination of Service Account usage, breadth of non-service account use, external system use, and the degree to which other data objects depend on this object.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "targets": [
    {
     "location": "US",
     "rawSql": "select distinct\n  concat(split(table_name, '/')[safe_offset(3)], '.', split(table_name, '/')[safe_offset(5)]) as table_name\n, importance_score\nfrom `leaner_query.rpt_bigquery_table_usage_daily`\nwhere report_date = current_date -1\n  and importance_score is not null\norder by importance_score desc\nlimit 25 -- maybe a rank instead of this later on"
    }
   ]
  },
  {
   "title": "Top 25 Priority Tables",
   "type": "table",
   "description": "This table contains the top 25 tables in your BQ instance which should have priority to be examined for optimization.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "location": "US",
     "rawSql": "select distinct\n  concat(split(table_name, '/')[safe_offset(3)], '.', split(table_name, '/')[safe_offset(5)]) as table_name\n, priority_score\nfrom `leaner_query.rpt_bigquery_table_usage_daily`\nwhere report_date = current_date -1\n  and priority_score is not null\norder by priority_score desc\nlimit 25 -- maybe a rank instead of this later on"
    }
   ]
  }
 ]
}